name: tests for lifebit-ai/spammer-wdl
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  basic_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Cromwell
        run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/53.1/cromwell-53.1.jar
          wget https://github.com/broadinstitute/cromwell/releases/download/53.1/womtool-53.1.jar
      - name: Basic validation of syntax of main.wdl using womtool
        run: |
          java -jar womtool-53.1.jar validate main.wdl
      - name: Run the pipeline using example inputs.json
        run: |
          java -jar cromwell-53.1.jar run main.wdl -i testdata/inputs.json -o options.json


